### ISSUE TITLE
Running Issue -- interface.cpp

### ISSUE THREAD

**Issue by wangru25** [mxfold/mxfold2#14]
Hi,

I got an error when I run ''mxfold2 predict test.fa''

Here is the error info

from .. import interface
ImportError: cannot import name 'interface' from 'mxfold2' (/mnt/home/wangru25/anaconda3/lib/python3.8/site-packages/mxfold2/__init__.py)

Would you please help me with this issue.

Thank you!

**Comment by jjtapia** [comment]
Confirming I get the same error from a python3.7 installation

Here is the full error stack

```
Traceback (most recent call last):
  File "/opt/conda/bin/mxfold2", line 5, in <module>
    from mxfold2.__main__ import main
  File "/opt/conda/lib/python3.7/site-packages/mxfold2/__main__.py", line 5, in <module>
    from .predict import Predict
  File "/opt/conda/lib/python3.7/site-packages/mxfold2/predict.py", line 13, in <module>
    from .fold.mix import MixedFold
  File "/opt/conda/lib/python3.7/site-packages/mxfold2/fold/mix.py", line 2, in <module>
    from .. import interface
ImportError: cannot import name 'interface' from 'mxfold2' (/opt/conda/lib/python3.7/site-packages/mxfold2/__init__.py)
```

**Comment by IseultLeahy** [comment]
I also got this same error. 

`Traceback (most recent call last):
  File "/opt/conda/envs/MXfold2/bin/mxfold2", line 5, in <module>
    from mxfold2.__main__ import main
  File "/opt/conda/envs/MXfold2/lib/python3.7/site-packages/mxfold2/__main__.py", line 5, in <module>
    from .predict import Predict
  File "/opt/conda/envs/MXfold2/lib/python3.7/site-packages/mxfold2/predict.py", line 13, in <module>
    from .fold.mix import MixedFold
  File "/opt/conda/envs/MXfold2/lib/python3.7/site-packages/mxfold2/fold/mix.py", line 2, in <module>
    from .. import interface
ImportError: cannot import name 'interface' from 'mxfold2' (/opt/conda/envs/MXfold2/lib/python3.7/site-packages/mxfold2/__init__.py)`

Was anyone able to resolve it?

**Comment by satoken** [comment]
Hi,

Thank you for the reports. I fixed the build issue.
You can build and install from the source distribution downloaded from [the release](https://github.com/mxfold/mxfold2/releases) as follows:

```
pip3 install mxfold2-0.1.2.tar.gz
```

Please try it.

**Comment by wangru25** [comment]
Thanks a lot!

Best,
Rui
